# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: default.yaml
  - model: softmax.yaml
  - paths: default.yaml
  - hydra: default.yaml

# task name, determines output directory path
task_name: "inference"
output_dir: osnet_x1_0_market_finetune
model_path: model.pth.tar-10
