# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: default.yaml
  - model: softmax.yaml
  - paths: default.yaml
  - hydra: default.yaml

# task name, determines output directory path
task_name: "inference"
model_path: ${paths.log_dir}/osnet_x1_0_market_origin/osnet_x1_0_market_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip.pth
